landing:
   path: /
   controller: App\Controller\LandingController

redirect_contact:
    path: /contact-me
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /
        permanent: true

blog_list:
   path: /blog
   controller: App\Controller\BlogListController
   format: html

blog_feed:
   path: /blog.{_format}
   controller: App\Controller\BlogListController
   format: xml|rss

sitemap:
   path: /sitemap.xml
   controller: App\Controller\SitemapController
   format: xml

blog_detail:
   path: /{slug}
   controller: App\Controller\BlogDetailController

